# Generated by Django 5.1.7 on 2026-01-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='spotify_url',
        ),
        migrations.AddField(
            model_name='song',
            name='apple_music_url',
            field=models.URLField(blank=True, help_text='Link to the song on Apple Music', null=True),
        ),
    ]
