# Generated by Django 5.1.7 on 2026-01-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='letter_covers/'),
        ),
    ]
