# Generated by Django 5.1.7 on 2026-01-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='era',
        ),
    ]
